codecov:
  token: 325cdf01-ca06-415a-9c06-0fabf97cab29

coverage:
  status:
    project:
      default: off
      frontend:
        flags: frontend
      backend:
        target: 50%
        flags: backend

flags:
  # filter the folder(s) you wish to measure by that flag
  backend:
    # only include files in the backend folder
    paths:
      - be/
  frontend:
    paths:
      - fe/
