codecov:
  token: 325cdf01-ca06-415a-9c06-0fabf97cab29

coverage:
  status:
    project:
      default: off
      kn-be-sd:
        target: 50%
        flags: kn-be-sd
      kn-be-se:
        target: 50%
        flags: kn-be-se
      kn-be-api:
        target: 50%
        flags: kn-be-api
      kn-fe-web:
        target: 50%
        flags: kn-fe-web

flags:
  kn-be-sd:
    paths:
      - be-sd/
  kn-be-se:
    paths:
      - be-se/
  kn-be-api:
    paths:
      - be-api/
  kn-fe-web:
    paths:
      - fe-web/kn
