version: '3'

services:
  kn-be-sd:
    image: kn-be-sd:latest  # tag after build
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - KN_INFRA_ELASTIC=infra-elastic
      - KN_INFRA_KIBANA=infra-kibana
      - KN_INFRA_GRAFANA=infra-grafana
      - KN_FE_WEB=kn-fe-web
