const constants = {
  FETCH_SURVEY_LIST: 'FETCH_SURVEY_LIST',
  FETCH_SURVEY_ITEM: 'FETCH_SURVEY_ITEM',
  PREVIEW_SURVEY: 'PREVIEW_SURVEY',
  SUBMIT_SURVEY: 'SUBMIT_SURVEY',
  ADD_ERROR: 'ADD_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
};

export default constants;
